### ISSUE TITLE
error while run the scripts

### ISSUE THREAD

**Issue by MachineGUN001** [molecularinformatics/Computational-ADME#1] opened 2023-05-24 16:07 UTC
hi, 
thanks for providing the codes for ML 

while the below code is implemented,
`python ADME_ML_public.py ADME_HLM.sdf -p 'LOG HLM_CLint (mL/min/kg)' -d FCFP4_rdMolDes -m LightGBM -w build`.

the error occured :

usage: ADME_ML_public.py [-h] -p PROPERTIES [-d DESCRIPTORS] [-m MODEL]
                         [-w WORKFLOW]
                         sdFile
ADME_ML_public.py: error: unrecognized arguments: HLM_CLint (mL/min/kg)'

I looked into the contents of ADME_HLM.sdf, and found the column name of 'LOG HLM_CLint (mL/min/kg)' looks right.
could you tell why the error appeared?
many thanks

**Comment by chengthefang** [comment] 2023-05-24 23:04
Hi, 

Thank you for trying this code. I just gave a try using the same script you used 
`python ADME_ML_public.py ADME_HLM.sdf -p 'LOG HLM_CLint (mL/min/kg)' -d FCFP4_rdMolDes -m LightGBM -w build`

It worked for me, and it generated two files of "trainSet.csv" and "model.rds" as the outputs. Would you mind giving another try? I am not sure if it is caused by your Python version and packages. Can you confirm if `import argparse` and `from argparse import *` work in your Python environment?

Cheng

**Comment by MachineGUN001** [comment] 2023-05-25 03:56
many thanks for your reply.

 the lib `import argparse and from argparse import *` work  in my Python environment, python 3.9.16.
also ther required packages have been installed accordlingly.

the error still occured, as below:
ADME_ML_public.py: error: unrecognized arguments: HLM_CLint (mL/min/kg)'

**Comment by MachineGUN001** [comment] 2023-05-25 04:16
hi,

I change the column name of '' into 'log_hlm', and use the below command line accordingly.
`python ADME_ML_public.py ADME_HLM.sdf -p 'log_hlm' -d FCFP4_rdMolDes -m LightGBM -w build `
the script looks work, but still some error occured as below.

[11:56:22] Can't kekulize mol.  Unkekulized atoms: 10 14 15 19 22 23
[11:56:24] Can't kekulize mol.  Unkekulized atoms: 2 4
[11:56:33] Can't kekulize mol.  Unkekulized atoms: 7 15
[11:56:36] Can't kekulize mol.  Unkekulized atoms: 1 9
[11:56:36] Can't kekulize mol.  Unkekulized atoms: 2 3 6 10
[11:56:36] Can't kekulize mol.  Unkekulized atoms: 1 11
[11:56:36] Can't kekulize mol.  Unkekulized atoms: 1 11
[11:56:39] Can't kekulize mol.  Unkekulized atoms: 3 7 8
[11:56:39] Can't kekulize mol.  Unkekulized atoms: 12 13
[11:56:42] Can't kekulize mol.  Unkekulized atoms: 2 4
[11:56:44] Tautomer enumeration stopped at 192 tautomers: max transforms reached
[11:56:49] Can't kekulize mol.  Unkekulized atoms: 3 5 8 10
[11:56:49] Can't kekulize mol.  Unkekulized atoms: 3 5 8 10
[11:56:54] Can't kekulize mol.  Unkekulized atoms: 15 16
[11:56:55] Can't kekulize mol.  Unkekulized atoms: 18 19
[11:56:59] Can't kekulize mol.  Unkekulized atoms: 7 9 14 18
[11:56:59] Can't kekulize mol.  Unkekulized atoms: 7 10 14 18
[11:56:59] Can't kekulize mol.  Unkekulized atoms: 7 10 14 18
[11:56:59] Can't kekulize mol.  Unkekulized atoms: 7 9 14 18
[11:57:01] Can't kekulize mol.  Unkekulized atoms: 2 3 6 10
[11:57:01] Can't kekulize mol.  Unkekulized atoms: 3 9
[11:57:01] Can't kekulize mol.  Unkekulized atoms: 3 9
[11:57:07] Can't kekulize mol.  Unkekulized atoms: 3 4
[11:57:07] Can't kekulize mol.  Unkekulized atoms: 16 17
[11:57:09] Tautomer enumeration stopped at 442 tautomers: max transforms reached
...
    self.handles = get_handle(
  File "[c:\Users\***\.conda\envs\aisynth\lib\site-packages\pandas\io\common.py](file:///C:/Users/***/.conda/envs/aisynth/lib/site-packages/pandas/io/common.py)", line 856, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'trainSet.csv'

two files of "trainSet.csv" and "model.rds" that you mentioned as the outputs were not generated. 

i am not sure if i changed the format of sdf file, which caused the errors. 
thanks for your help.

**Comment by chengthefang** [comment] 2023-05-25 13:55
Hi,

It seems like it didn't generate the "trainSet.csv" file that is used for model build. Can you share the complete output message so that maybe we can find the reason? You can mute the RDKit logging info to avoid the long output.

A few other comments:
1. The messages of "Can't kekulize mol" and "Tautomer enumeration" are RDKit logging info. They are generated during the molecule standardization step. You can turn it off by adding the following codes in your Python script:
```
from rdkit import RDLogger
lg = RDLogger.logger()
lg.setLevel(RDLogger.CRITICAL)
```

2. The previous error when using "'LOG HLM_CLint (mL/min/kg)'" might be because of the operating system difference. The Windows machine deal with I/O format differently from Linux/Mac OS, in particular how to deal with space and other special symbols such as parenthesis and slash/backslash.

Cheng

**Comment by MachineGUN001** [comment] 2023-05-25 15:55
> Hi,
> 
> It seems like it didn't generate the "trainSet.csv" file that is used for model build. Can you share the complete output message so that maybe we can find the reason? You can mute the RDKit logging info to avoid the long output.
> 
> A few other comments:
> 
> 1. The messages of "Can't kekulize mol" and "Tautomer enumeration" are RDKit logging info. They are generated during the molecule standardization step. You can turn it off by adding the following codes in your Python script:
> 
> ```
> from rdkit import RDLogger
> lg = RDLogger.logger()
> lg.setLevel(RDLogger.CRITICAL)
> ```
> 
> 2. The previous error when using "'LOG HLM_CLint (mL/min/kg)'" might be because of the operating system difference. The Windows machine deal with I/O format differently from Linux/Mac OS, in particular how to deal with space and other special symbols such as parenthesis and slash/backslash.
> 
> Cheng

thanks for your kind explanation.

here is the complete error info, after shutdown RDKit whiny logging


```

>  'cp' is not recognized as an internal or external command,
> operable program or batch file.
> Traceback (most recent call last):
>   File "d:\Workshop\...\Computational_ADME\ML\ADME_ML_public.py", line 337, in <module>
>     train_df = pd.read_csv("trainSet.csv")
>   File "c:\Users\***\.conda\envs\aisynth\lib\site-packages\pandas\util\_decorators.py", line 211, in wrapper
>     return func(*args, **kwargs)
>   File "c:\Users\***\.conda\envs\aisynth\lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
>     return func(*args, **kwargs)
>   File "c:\Users\***\.conda\envs\aisynth\lib\site-packages\pandas\io\parsers\readers.py", line 950, in read_csv
>     return _read(filepath_or_buffer, kwds)
>   File "c:\Users\***\.conda\envs\aisynth\lib\site-packages\pandas\io\parsers\readers.py", line 605, in _read
>     parser = TextFileReader(filepath_or_buffer, **kwds)
>   File "c:\Users\***\.conda\envs\aisynth\lib\site-packages\pandas\io\parsers\readers.py", line 1442, in __init__
>     self._engine = self._make_engine(f, self.engine)
>   File "c:\Users\***\.conda\envs\aisynth\lib\site-packages\pandas\io\parsers\readers.py", line 1735, in _make_engine
>     self.handles = get_handle(
>   File "c:\Users\***\.conda\envs\aisynth\lib\site-packages\pandas\io\common.py", line 856, in get_handle
>     handle = open(
> FileNotFoundError: [Errno 2] No such file or directory: 'trainSet.csv'

```
cp is a unix command, so it doesn't work on Windows.
my PC system is windows 10, rdkit version 2022.09.5

could you pleases provide suggestions to fix the issues?
many many thanks,


Shengyang

**Comment by MachineGUN001** [comment] 2023-05-25 16:21
hereby, I replaced 'cp' with 'copy' as well as 'rm' with 'del' in the script.
the command can work well under windows 10.

two files you mentioned including model.rds and transet.csv were generated.
that scripts work for me. 

many thanks again for your kind help and explanation.

Could you please provide some instructions how to run the model generated by scripts for predicting the unknow molecules?
many thanks,

best,

Shengyang

**Comment by chengthefang** [comment] 2023-05-25 22:55
Hi Shengyang,

It's good to know you sorted it out. Yes, we only tested the codes with Linux and Mac OS, not on Windows. But subtle modifications will make the codes work on Windows machine. 

You can run `python ADME_ML_public.py test.sdf -d FCFP4_rdMolDes -w prediction` where your test molecules are stored in test.sdf. You have to make sure that the trained model "model.rds" resides in the same directory. 

Also, since the codes work for you now, shall we close this ticket?

Cheng

**Comment by MachineGUN001** [comment] 2023-05-26 00:54
hi, Cheng,

thanks for your help to provide the command line for predicting test molecules.
could you please also provide a example file such as test.sdf in github folder, 
which could let us also understand that those fields must be included in the sdf?

for one another question, while I run the command, and find the below error

```
> usage: ADME_ML_public.py [-h] -p PROPERTIES [-d DESCRIPTORS] [-m MODEL]
                         [-w WORKFLOW]
                         sdFile

ADME_ML_public.py: error: the following arguments are required: -p/--properties
```

is ` -p/--properties` necessary for implementing the script?

many thanks,

best,
Shengyang

**Comment by chengthefang** [comment] 2023-05-26 01:13
Hi Shengyang,

Good catch. I set up --p as the required property to enforce that we don't forget put the property argument in model build and validation. You can run `python ADME_ML_public.py ADME_HLM.sdf -d FCFP4_rdMolDes -p 'XXX' -w prediction ` by using any arbitrary property string. Here I used ADME_HLM.sdf as the input example. 

Alternatively, you can remove "required=True" in the python code where the property argument is defined `parser.add_argument("-p","--properties",required=True, ....`. Then you should be able to run `python ADME_ML_public.py ADME_HLM.sdf -d FCFP4_rdMolDes -w prediction` without problems.

Let me know if it works for you.

Cheng

**Comment by MachineGUN001** [comment] 2023-05-26 01:45
> Hi Shengyang,
> 
> Good catch. I set up --p as the required property to enforce that we don't forget put the property argument in model build and validation. You can run `python ADME_ML_public.py ADME_HLM.sdf -d FCFP4_rdMolDes -p 'XXX' -w prediction ` by using any arbitrary property string. Here I used ADME_HLM.sdf as the input example.
> 
> Alternatively, you can remove "required=True" in the python code where the property argument is defined `parser.add_argument("-p","--properties",required=True, ....`. Then you should be able to run `python ADME_ML_public.py ADME_HLM.sdf -d FCFP4_rdMolDes -w prediction` without problems.
> 
> Let me know if it works for you.
> 
> Cheng

hi, Cheng,

thanks for your quick feedback.
I tried the method you suggested and the script looks work. 
the new file, named by 'ADME_HLM_cADME.sdf' was generated.
however, I cannot find any predicted values in this file, which I open by using datawarrior (sdf viewer). also the scree

- [ ] 

- [ ] 
![00368-455134891](https://github.com/molecularinformatics/Computational-ADME/assets/16698635/bd30e444-71b4-485e-b49b-ea6218b52f39)

Please check the screenshots I uploaded， of which seems a bit wrong ah
sorry to bother you about the new issues. many thanks,


Shengyang

**Closed as completed** 2023-05-26 02:04 UTC
